// This tests a reactor that contains another reactor and also
// has its own reaction that routes inputs to the contained reactor.

// FIXME: Find a way to terminate with failure and address target attributes

target TypeScript{
    timeout : 2 sec
};
//(
//  run = "bin/SendingInside -fast -timeout 10 sec"
//);
reactor Printer {
    input x:number;
    state count:number(1);
    reaction(x) {=
        console.log("Inside reactor received: " + x);
        if ((x as number) != count) {
            console.log("FAILURE: Expected " + count);
            util.exec.failure();
            //throw new Error("FAILURE: Expected " + (this.state as any).count);
        }
        count++;
    =}
}
main reactor SendingInside {
    state count:number(0);
    timer t(0, 1 sec);
    p = new Printer();
    reaction(t) -> p.x {=
        count++;
        p.x.set(count);
    =}
}